# Generated by Django 4.1.7 on 2023-06-21 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='owner',
            new_name='owner_in',
        ),
    ]
